---
title: "getting-started"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{getting-started}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


# Installation

You can install the development version of vegetablesSriLanka from GitHub with:

``` r
# install.packages("pak")
pak::pak("thiyangt/vegetablesSriLanka")
```

# Load  package and data

```{r example}
library(vegetablesSriLanka)
data("vegetables.srilanka")
head(vegetables.srilanka)
tail(vegetables.srilanka)
```



# Example

## Fill missing gaps

```{r}
filled <- fillgaps_vegetable_prices(
   data = vegetables.srilanka,
   item = "Carrot",
   market = "Dambulla",
   type = "Retail"
 )
filled
```


## Plot data

```{r, message=FALSE, warning=FALSE}
plot_vegetable_prices(
   data = vegetables.srilanka,
   item = "Carrot",
   market = "Dambulla",
   type = "Retail"
 )
```



## Data Quality Analysis

```{r, warning=FALSE, message=FALSE}
visualize_missingness(
  data = vegetables.srilanka,
  group_var = "Item",
  target_var = "Price"
 )
```
